### ISSUE TITLE
feature request: unit test, example file

### ISSUE THREAD

**Issue by shimpe** [madskjeldgaard/cookiecutter-quark#2]
In addition to a basic quark, I'd propose to also generate a basic unit test for the quark.

While making quarks it took me a while to find out that only .sc files are compiled and .scd files are ignored. This makes it possible to include small examples using the quark as .scd files. Perhaps it makes sense to also generate an .scd file instantiating the example quark?

**Comment by madskjeldgaard** [comment]
you’re right about that typo!

Can you show me an example of what you mean regarding the unit test? It sounds very interesting but I’ve never done anything like that.

Thanks!


Best Regards,
Mads Kjeldgaard

**Comment by shimpe** [comment]
A unit test is a piece of code that automatically tests your code by feeding in values and checking the outputs against expected answers.This allows for easily testing all kinds of scenarios and corner cases, some of which may be hard to trigger on purpose by just casually trying out some things in larger projects. Not only does it increase the code quality, but it also helps you keeping everything working correctly when you start to reorganize and clean up your code.

E.g. in Panola https://github.com/shimpe/panola/tree/master/Classes I added a PanolaTester class, which - when instantiated - runs all the unit tests for panola. Pretty much every part of it is tested automatically using unit tests.

In https://github.com/shimpe/temporaldict/tree/master/Classes I added the test class in a separate Test folder. Maybe it makes sense to keep tests separated from code.

**Comment by shimpe** [comment]
Also would it be possible to select and include a license file?

**Comment by madskjeldgaard** [comment]
I can def indclude the license thing. Let me have a look at it later. 

Regarding the unit testing. 

If we restructure the main class **{{cookiecutter.quark_name}}.sc** like so: 
```
{{cookiecutter.quark_name}} {
	// this is a normal constructor method
 *new { | thing1, thing2|
		^super.new.init( thing1, thing2 );
	}

	init { | thing1, thing2 |
		^this.addTwoThings(thing1, thing2);
	}

	addTwoThings{ |thing1=1, thing2=1|
		^thing1 + thing2;
	}
}
```

And then add a subfolder in the classes folder called Tests containing a file called **{{cookiecutter.quark_name}}Test.sc**:

```
{{cookiecutter.quark_name}}Test1 : UnitTest {
	test_check_addition{
		var result = {{cookiecutter.quark_name}}.new(2,2);

		this.assertEquals(result, 4)
	}
}


{{cookiecutter.quark_name}}Tester {
	*new {
		^super.new.init();
	}

	init {
		{{cookiecutter.quark_name}}Test1.run;
	}
}
```
Is that sort of how you imagined? otherwise let me know if you have change ideas

**Comment by madskjeldgaard** [comment]
A license choice has now been added. Let me know what you think of the unit test solution and I'll include that as well.

**Comment by shimpe** [comment]
It may not be needed to redefine main just to be able to write a test. Maybe it suffices to write something like:

test_check_classname {
  var result = {{cookiecutter.quark_name}}.new;
  this.assertEquals(result.class == {{cookiecutter.quark_name}});
}

**Comment by madskjeldgaard** [comment]
Okay, good idea!  so a test file that looks like this then? 

```
{{cookiecutter.quark_name}}Test1 : UnitTest {
	test_check_classname {
		var result = {{cookiecutter.quark_name}}.new;
		this.assertEquals(result.class == {{cookiecutter.quark_name}});
	}
}


{{cookiecutter.quark_name}}Tester {
	*new {
		^super.new.init();
	}

	init {
		{{cookiecutter.quark_name}}Test1.run;
	}
}

```

**Comment by shimpe** [comment]
yes that looks about right to me (although i would still suggest to generate a sample project and verify that it really succeeds :))

it would be great to have a sample unit test because i often struggle to start a new one from scratch (meaning i have to lookup how to do it every time)

**Comment by madskjeldgaard** [comment]
Yes I agree – it's a nice feature, also it serves as a nice reminder to actually do testing. It's a good point for this template to show a bare bone, but ideal structure for a quark so it's just perfect to have testing there too. Also, half of the UnitTest docs are currently dead in SC but it seems it's getting fixed. I'll do a bit of testing (no pun intended) and commit the changes

**Comment by madskjeldgaard** [comment]
Okay, it's done. See the main repo now :) 

Thanks for the help + suggestions

**Comment by shimpe** [comment]
Great! Thanks.
